[2025-04-13 17:08:22 +0000] [1150] [INFO] Starting gunicorn 23.0.0
[2025-04-13 17:08:22 +0000] [1150] [INFO] Listening at: unix:/home/e-interativo.com.br/e-interativo.sock (1150)
[2025-04-13 17:08:22 +0000] [1150] [INFO] Using worker: sync
[2025-04-13 17:08:22 +0000] [1151] [INFO] Booting worker with pid: 1151
[2025-04-13 17:08:22 +0000] [1152] [INFO] Booting worker with pid: 1152
[2025-04-13 17:08:22 +0000] [1154] [INFO] Booting worker with pid: 1154
[2025-04-13 17:08:22 +0000] [1155] [INFO] Booting worker with pid: 1155
[2025-04-13 17:12:51 +0000] [1150] [INFO] Handling signal: int
[2025-04-13 17:12:51 +0000] [1151] [INFO] Worker exiting (pid: 1151)
[2025-04-13 17:12:51 +0000] [1152] [INFO] Worker exiting (pid: 1152)
[2025-04-13 17:12:51 +0000] [1154] [INFO] Worker exiting (pid: 1154)
[2025-04-13 17:12:51 +0000] [1155] [INFO] Worker exiting (pid: 1155)
[2025-04-13 17:12:51 +0000] [1150] [INFO] Shutting down: Master
[2025-05-01 17:38:23 +0000] [118619] [INFO] Starting gunicorn 23.0.0
[2025-05-01 17:38:23 +0000] [118619] [INFO] Listening at: unix:/home/e-interativo.com.br/e-interativo.sock (118619)
[2025-05-01 17:38:23 +0000] [118619] [INFO] Using worker: sync
[2025-05-01 17:38:23 +0000] [118620] [INFO] Booting worker with pid: 118620
[2025-05-01 17:38:23 +0000] [118620] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2025-05-01 17:38:23 +0000] [118620] [INFO] Worker exiting (pid: 118620)
[2025-05-01 17:38:23 +0000] [118619] [ERROR] Worker (pid:118620) exited with code 3
[2025-05-01 17:38:23 +0000] [118619] [ERROR] Shutting down: Master
[2025-05-01 17:38:23 +0000] [118619] [ERROR] Reason: Worker failed to boot.
[2025-05-01 17:38:31 +0000] [118621] [INFO] Starting gunicorn 23.0.0
[2025-05-01 17:38:31 +0000] [118621] [INFO] Listening at: unix:/home/e-interativo.com.br/e-interativo.sock (118621)
[2025-05-01 17:38:31 +0000] [118621] [INFO] Using worker: sync
[2025-05-01 17:38:31 +0000] [118622] [INFO] Booting worker with pid: 118622
[2025-05-01 17:38:31 +0000] [118622] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/e-interativo.com.br/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2025-05-01 17:38:31 +0000] [118622] [INFO] Worker exiting (pid: 118622)
[2025-05-01 17:38:31 +0000] [118621] [ERROR] Worker (pid:118622) exited with code 3
[2025-05-01 17:38:31 +0000] [118621] [ERROR] Shutting down: Master
[2025-05-01 17:38:31 +0000] [118621] [ERROR] Reason: Worker failed to boot.
[2025-05-01 17:43:08 +0000] [118741] [INFO] Starting gunicorn 23.0.0
[2025-05-01 17:43:08 +0000] [118741] [INFO] Listening at: unix:/home/e-interativo.com.br/e-interativo.sock (118741)
[2025-05-01 17:43:08 +0000] [118741] [INFO] Using worker: sync
[2025-05-01 17:43:08 +0000] [118742] [INFO] Booting worker with pid: 118742
[2025-05-01 17:43:08 +0000] [118743] [INFO] Booting worker with pid: 118743
[2025-05-01 17:43:09 +0000] [118744] [INFO] Booting worker with pid: 118744
[2025-05-01 17:43:09 +0000] [118745] [INFO] Booting worker with pid: 118745
[2025-05-01 18:13:36 +0000] [118741] [INFO] Handling signal: hup
[2025-05-01 18:13:36 +0000] [118741] [INFO] Hang up: Master
[2025-05-01 18:13:36 +0000] [119044] [INFO] Booting worker with pid: 119044
[2025-05-01 18:13:36 +0000] [119046] [INFO] Booting worker with pid: 119046
[2025-05-01 18:13:36 +0000] [119045] [INFO] Booting worker with pid: 119045
[2025-05-01 18:13:36 +0000] [118741] [ERROR] Worker (pid:118743) was sent SIGHUP!
[2025-05-01 18:13:36 +0000] [118741] [ERROR] Worker (pid:118744) was sent SIGHUP!
[2025-05-01 18:13:36 +0000] [118741] [ERROR] Worker (pid:118742) was sent SIGHUP!
[2025-05-01 18:13:36 +0000] [118741] [ERROR] Worker (pid:118745) was sent SIGHUP!
[2025-05-01 18:13:36 +0000] [118741] [INFO] Handling signal: hup
[2025-05-01 18:13:36 +0000] [118741] [INFO] Hang up: Master
[2025-05-01 18:13:36 +0000] [119047] [INFO] Booting worker with pid: 119047
[2025-05-01 18:13:36 +0000] [119048] [INFO] Booting worker with pid: 119048
[2025-05-01 18:13:36 +0000] [119049] [INFO] Booting worker with pid: 119049
[2025-05-01 18:13:36 +0000] [119050] [INFO] Booting worker with pid: 119050
[2025-05-01 18:13:37 +0000] [119051] [INFO] Booting worker with pid: 119051
[2025-05-01 18:13:38 +0000] [119044] [INFO] Worker exiting (pid: 119044)
[2025-05-01 18:13:39 +0000] [118741] [ERROR] Worker (pid:119044) was sent SIGTERM!
[2025-05-01 18:13:39 +0000] [119045] [INFO] Worker exiting (pid: 119045)
[2025-05-01 18:13:39 +0000] [119047] [INFO] Worker exiting (pid: 119047)
[2025-05-01 18:13:39 +0000] [119046] [INFO] Worker exiting (pid: 119046)
[2025-05-01 18:13:39 +0000] [118741] [ERROR] Worker (pid:119045) was sent SIGTERM!
